site_name: PiRecon Doc 
# repo_url: https://github.com/tech-pi/SRF_NEF
# repo_name: GitHub
site_description: Docs for Pitech recon toolkits (SRFNEF)
site_author: Minghao Guo
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
nav: 
    - 'Introduction': 'index.md'
    - 'Architecture': 'arch.md'
    - 'User Guide': 'use.md'
    - 'Programmer Guide':
        - 'General': 'program_guide/general.md' 
        - 'base模块': 'program_guide/base.md'
    - 'Example':
        - 'Data Process': 'data_proc.md'
    - 'About': 'about.md'

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs
